import { AllCourse } from '../components/types/course';
import popularCoursesImage from '../assets/images/popular-courses.png';

const courses: AllCourse[] = [
    {
      id: '1',
      title: 'Complete Frontend development with a bootcamp',
      author: 'John Doe',
      category:'Frontend Development',
      totalLecture: 6,
      totalStudents: 10,
      lastUpdated: '12-02-2024',
      originalPrice: 600,
      currentPrice: 300,
      type:"paid",
      imageUrl: popularCoursesImage,
    },
    {
      id: '2',
      title: 'Complete Backend development with a bootcamp',
      author: 'John Doe',
      category:'Backend Development',
      totalLecture: 6,
      totalStudents: 10,
      lastUpdated: '12-02-2024',
      originalPrice: 600,
      currentPrice: 300,
      type:"paid",
      imageUrl: popularCoursesImage,
    },
    {
      id: '3',
      title: 'Complete Backend development with a bootcamp',
      author: 'Kenny White',
      category:'Backend Development',
      totalLecture: 6,
      totalStudents: 10,
      lastUpdated: '12-02-2024',
      originalPrice: 299,
      currentPrice: 'Free',
      type:"free",
      imageUrl: popularCoursesImage,
    },
    {
      id: '4',
      title: 'Complete Fullstack development with a bootcamp',
      author: 'John Doe',
      category:'Fullstack Development',
      totalLecture: 6,
      totalStudents: 10,
      lastUpdated: '12-02-2024',
      originalPrice: 299,
      currentPrice: 'Free',
      type:"free",
      imageUrl: popularCoursesImage,
    },
    {
      id: '5',
      title: 'Complete Fullstack development with a bootcamp',
      author: 'Kenny White',
      category:'Fullstack Development',
      totalLecture: 6,
      totalStudents: 10,
      lastUpdated: '12-02-2024',
      originalPrice: 299,
      currentPrice: 'Free',
      type:"free",
      imageUrl: popularCoursesImage,
    },
    {
      id: '6',
      title: 'Complete Fullstack development with a bootcamp',
      author: 'John Doe',
      category:'Fullstack Development',
      totalLecture: 6,
      totalStudents: 10,
      lastUpdated: '12-02-2024',
      originalPrice: 299,
      currentPrice: 'Free',
      type:"free",
      imageUrl: popularCoursesImage,
    },
    {
      id: '7',
      title: 'Complete App development with a bootcamp',
      author: 'Kenny White',
      category:'App Development',
      totalLecture: 6,
      totalStudents: 10,
      lastUpdated: '12-02-2024',
      originalPrice: 299,
      currentPrice: 'Free',
      type:"free",
      imageUrl: popularCoursesImage,
    },
    {
      id: '8',
      title: 'Complete App development with a bootcamp',
      author: 'John Doe',
      category:'App Development',
      totalLecture: 6,
      totalStudents: 10,
      lastUpdated: '12-02-2024',
      originalPrice: 299,
      currentPrice: 'Free',
      type:"free",
      imageUrl: popularCoursesImage,
    },
    {
      id: '9',
      title: 'Complete App development with a bootcamp',
      author: 'John Doe',
      category:'App Development',
      totalLecture: 6,
      totalStudents: 10,
      lastUpdated: '12-02-2024',
      originalPrice: 299,
      currentPrice: 'Free',
      type:"free",
      imageUrl: popularCoursesImage,
    },
    {
      id: '10',
      title: 'Complete UI/UX Design with a bootcamp',
      author: 'Kenny White',
      category:'UI/UX Design',
      totalLecture: 6,
      totalStudents: 10,
      lastUpdated: '12-02-2024',
      originalPrice: 299,
      currentPrice: 'Free',
      type:"free",
      imageUrl: popularCoursesImage,
    },
    {
      id: '11',
      title: 'Complete UI/UX Designt with a bootcamp',
      author: 'Kenny White',
      category:'UI/UX Design',
      totalLecture: 6,
      totalStudents: 10,
      lastUpdated: '12-02-2024',
      originalPrice: 299,
      currentPrice: 'Free',
      type:"free",
      imageUrl: popularCoursesImage,
    },
    {
      id: '12',
      title: 'Complete Frontend development with a bootcamp',
      author: 'Kenny White',
      category:'Frontend Development',
      totalLecture: 6,
      totalStudents: 10,
      lastUpdated: '12-02-2024',
      originalPrice: 299,
      currentPrice: 'Free',
      type:"free",
      imageUrl: popularCoursesImage,
    },
  ];
  export default courses